### ISSUE TITLE
cmmk_set_single_key fails on Masterkeys Pro S

### ISSUE THREAD

**Issue by Programmerino** [chmod222/libcmmk#3]
Hello! I was looking at getting this to work with my Masterkeys Pro S (US) keyboard. I was wondering how I can create a proper keymap for the keyboard and also just to get it to work with the S edition.

**Comment by chmod222** [comment]
Hey, thanks for the offer.

In order to get the library to work with the S version, I would think that you have to change the CMMK_USB_VENDOR and CMMK_USB_PRODUCT values to whatever IDs the S version is using. This can easily be found out using `lsusb` on Linux and the device properties view in Windows.

Unless CM uses a different protocol for the S versions (which would be very surprising) the new USB IDs should be all you need to change in order to get it working.

Mapping out the keys is a bit of a manual process and not very elegant. The way I generated my EU/GER Keymap was by bringing my keyboard into manual mode via

    cmmk_set_control_mode(dev, CMMK_MANUAL);

and then simply iterating over all integers from 0 upwards, calling

    cmmk_set_single_key(dev, i, &(struct rgb){0xff, 0xff, 0xff})

with a prompt to enter the name of the button that has just lit up on the keyboard. At the same time I had it outut the name that was entered alongside the index used to light it up to stderr and redirected that to a file.

From there on it was simply a matter of turning that dump of... 

    KEY_NAME = index

...into an enum to be used.

**Comment by Programmerino** [comment]
My keyboard doesn't seem to respond to cmmk_set_single_key at all, however the test application works fine after changing the vendor id and product id in libcmmk.c without any further editing...

**Comment by chmod222** [comment]
That's intersting, what does this program do?

```c
#include "libcmmk.h"

#include <unistd.h> /* sleep() */

#include <signal.h>
#include <stdio.h>
#include <stdlib.h>


int g_stop = 0;

static void interrupted(int sig)
{
	(void)sig;

	g_stop = 1;
}

int cmmk_set_profile(struct cmmk *dev, int prof);

int main(int argc, char** argv)
{
	size_t i;
	struct rgb test_color = { 0xff, 0x00, 0xff };

	(void)argc;
	(void)argv;

	struct cmmk state;

	if (cmmk_attach(&state) != 0)
		return 1;

	cmmk_set_control_mode(&state, CMMK_MANUAL);
	signal(SIGINT, interrupted);

	for (i = 0; (i < 128) && !g_stop; ++i) {
		cmmk_set_single_key(&state, i, &test_color);
		sleep(1);
	}

	cmmk_set_control_mode(&state, CMMK_FIRMWARE);
	cmmk_detach(&state);

	return 0;
}
```

**Comment by Programmerino** [comment]
Still nothing...

**Comment by bonnee** [comment]
I'm having the same exact issues as @SkyrisBactera on my Italian MasterKeys Pro L White. cmmk_set_single_key does nothing and also the effects aren't working or they code is different.

**Comment by puddyput** [comment]
hey @131072 and @Bonnee - did you run it with sudo? I had the same problem or segfaults when I didn't.
 otherwise you have to set a udev rule (afaik)

sorry for posting in this old issue, but since I came here for debugging my problem I figured it might help the next person

**Comment by Programmerino** [comment]
Honestly I don't remember what I was trying to do when I posted this, but after installing the ```libcmmk-git``` package, the cmmk-test binary does start a rainfall effect with one key cycling through the RGB spectrum when ran with sudo. I'll close the issue for now
