### ISSUE TITLE
Help with mapping US layout and MasterKeys Pro S

### ISSUE THREAD

**Issue by pokonski** [chmod222/libcmmk#5]
Hey @chmod222!

I mapped keys for my MasterKeys Pro S with US layout to work with your lib. Are you accepting PRs or is it abandoned?

**Comment by HaoZeke** [comment]
I was just about to start on a Pro L US layout.. I guess you ought to try a PR.

**Comment by chmod222** [comment]
Hey,

the project is not entirely abandoned, no.  But it currently does everything I needed it to do when I first set out writing it, so I don't have any immediate or long term plans right now.

That said, do feel free to send me pull requests.  I can't really test different layouts because I only have one model, but I'll get around to merging them if they compile cleanly.

**Comment by pokonski** [comment]
@HaoZeke do you have a full width keyboard? Mine doesn't have numpad so can't map that part.

**Comment by HaoZeke** [comment]
Yup, I have the large variety which includes the numpad.

**Comment by ku1ik** [comment]
I'd be happy to help test the PR on my Pro S (US) 🙌

**Comment by pokonski** [comment]
@HaoZeke @sickill have a look! https://github.com/chmod222/libcmmk/pull/7 

My C is super rusty so it can definitely be improved.
